### ISSUE TITLE
Allow "Deploy" button to link to many repos

### ISSUE THREAD

**Issue by singhkay** [projectkudu/slingshot#26]
I’ve setup a model repo - https://github.com/azurermtemplates/azurermtemplates 

This has a template that is linked to another repo and also a hosted template. The README.md file is expected to have an index of 40-50 templates hosted in other repos. As it looks currently, I’ll need to have 1-1 ratio of Deploy buttons, so 40-50 of them on one page. A feature that I think might be worth it is if we had one deploy to azure button that could let you choose which template to deploy from an array of repo urls passed in as a parameter. 

I’m thinking something like this in the code
< a href="https://azuredeploy.net/?repository=(https://github.com/user/repo, https://github.com/user/repo2, https://github.com/user/repo3, https://github.com/user/repo4)" target="_blank">
    <img src="http://azuredeploy.net/deploybutton.png"/>
</a >

This could be useful for an index page. Clicking the button lets you choose which template to deploy.

**Comment by davidebbo** [comment]
Note sure I like this idea. The problem is that once you get to the place that shows you the dropdown, you would not have much context to choose which one you want (and a dropdown with 50 choices can get messy). By contrast, by hand crafting a source page that organizes all the buttons, you get to put the right context around them, and if needed organize them into meaningful sections. I would argue that if you have 50, you'd probably want to create multiple pages to cover various subfeatures more cleanly.

**Comment by Tuesdaysgreen** [comment]
I agree with David.  The beauty of the button is that it keeps deployment simple by tying the click of a button to a specific project.  I don't think it makes at the moment to introduce a gallery-like capability to such a simple deployment process, when all the user is going to see is a drop-down of various project URLs.  It might make more sense if each repo item had metadata that could be displayed in a nice way with context about what it is, but if we're going to go that far, we may as well just have your parent readme point to the other projects which each have their own readme's and buttons.

**Comment by singhkay** [comment]
Sounds good guys, we had a discussion on the team and decided not to pursue this for the moment
