### ISSUE TITLE
Failed to decode JWT Token payload

### ISSUE THREAD

**Issue by altrive** [projectkudu/slingshot#27]
When I use deploy to Azure button. Following error occurs.

> "The input is not a valid Base-64 string as it contains a non-base 64 character, 
> more than two padding characters, or an illegal character among the padding characters. "

Exception raised at Convert.FromBase64String(base64) method of GetTokenAPI endpoint.
at <https://github.com/projectkudu/slingshot/blob/master/Slingshot.Api/Controllers/ARMController.cs#L70>

I confirmed my Jwt token contains '-' charactors, and decoding failed.
It need to use Base64 Url decode. instead of Base64.

For example, following library(System.IdentityModel.Tokens.Jwt) use Base64 URL decode:
https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/blob/master/src/System.IdentityModel.Tokens.Jwt/Base64UrlEncoder.cs#L101-L133

**Comment by davidebbo** [comment]
Strange. Do you get this consistently? e.g. if you go to https://github.com/Tuesdaysgreen/HelloWorlddemo and click the button, it happens?

What if you try from an incognito window? Do you get an Azure login dialog, and does the error still happen after you log in?

Another test: what happens when you go to https://portal.azure.com/?

**Comment by altrive** [comment]
>e.g. if you go to https://github.com/Tuesdaysgreen/HelloWorlddemo and click the button, it happens?

Yes it always happens when using specific MicrosoftAccout.
I've using 3 Microsoft Account. and this problem occurs when using 1 specific accounts. 

> What if you try from an incognito window?
Error still happens.  

>Another test: what happens when you go to https://portal.azure.com/?
There is no problems to login PreviewPortal.

**Comment by davidebbo** [comment]
@suwatch maybe you'll have some thoughts here?

**Comment by suwatch** [comment]
@altrive I think I understand the bug and what the fix should be.   I just want to make sure our fix did address the issue.   Is there a way you can share us fiddler or chrome network HAR log (preserved on) during login?   You can send to me via email suwatch@microsoft.com.   

<b>Note</b> that the log will contain your id_token for identification.  This token has a 1 hr validity.   Meaning do wait one hour till it expired before you send the log to us.  We can only use for debugging purpose.  Since it is expired, we can't use it for access/auth - just to be safe.

**Comment by suwatch** [comment]
@davidebbo Since it only affects slingshot and deployment is fast (in case we have to revert or apply another fix).   Should we just go ahead and fix it so @altrive can validate directly?

**Comment by altrive** [comment]
I've tested your fix in local environments. and it works as I expected.
I hope this fix is deployed to production environment.

**Comment by suwatch** [comment]
@altrive awesome then.  I have merged to master.  We will deploy as soon as possible ETA tomorrow.

**Comment by davidebbo** [comment]
@altrive the fix should be deployed. Could you give it a try?

**Comment by altrive** [comment]
Thanks for your quick fix!
I've confirmed my custom template successfully deployed.
