### ISSUE TITLE
Allow no repo specified link to work from deep inside the repo as well

### ISSUE THREAD

**Issue by singhkay** [projectkudu/slingshot#35]
This code doesn't work here - https://github.com/azurermtemplates/azurermtemplates/tree/master/create-storage-account

<a href="https://deploy.azure.com" target="_blank">
    <img src="http://azuredeploy.net/deploybutton.png"/>
</a>

Users need to specify the deep repo link in their fork but when their PR is accepted this link still points back to their fork where their fork template could get updated without the official repo template getting updated. Allowing the non-repo specified link to work from deep repo will ensure user's template always gets deployed from the repo it is hosted in.

**Comment by davidebbo** [comment]
Hmmm, I thought we supported that. @Tuesdaysgreen ?

**Comment by singhkay** [comment]
I think it works if we specified the deep repo link on the code but it doesn't work without it

**Comment by davidebbo** [comment]
Have you tried with the button going to https://azuredeploy.net/ instead of https://deploy.azure.com/? I don't think we ever got the referrer working with the latter. For now, the button always uses https://azuredeploy.net/. And I don't think this relates to it being deep in a repo. Even at the root, I don't think this would work.

**Comment by singhkay** [comment]
@davidebbo That didn't work either, I get taken to https://deploy.azure.com/#/form/infohome

**Comment by davidebbo** [comment]
Ok, but we're clear that https://deploy.azure.com/ never works, right?

**Comment by singhkay** [comment]
@davidebbo yep that didn't work as well from the root repo here https://github.com/singhkay/VM-DSC-Extension-IIS-Server

**Comment by Tuesdaysgreen** [comment]
I responded to @singhkay by email but I'll respond here as well.  Please make sure to use https://azuredeploy.net.  (It MUST be https and not http).  Unfortunately at the moment https://deploy.azure.com won't work directly because we can lose the referrer header during the sign-in process due to all of the redirection.  The azuredeploy.net site fixes that because it doesn't require sign-in to get there.  Once the page loads, it grabs the referrer header and then redirects you with a query string to deploy.azure.com.

**Comment by davidebbo** [comment]
Thanks Elliott. So bottom line: change the button's link from `http://azuredeploy.net/` to `https://azuredeploy.net/` and it should work.

**Comment by singhkay** [comment]
Thanks guys, that solved it :)
