### ISSUE TITLE
Deploy Page does not complete

### ISSUE THREAD

**Issue by DRediske** [projectkudu/slingshot#68]
During the deployment, slingshot does not report completion of deployment. It will indefinitely stay on this step, though the deployment has completed.  

![notfinished](https://cloud.githubusercontent.com/assets/8104702/15050527/405ccf40-12a9-11e6-926b-0ff7b026d0a1.PNG)

Error below was returned from a request for deployment status from ARM. 
`Failed to load resource: the server responded with a status of 404 (Not Found)`

**Comment by shrimpy** [comment]
@DRediske 

I found the issue. root cause is your template is generate random site name within the template, which Slingshot has no context of it, which lead to the 404 error.
Please update your template to expose siteName as input parameter, and generate the random site name as default value when define your siteName parameter.
 
Below blog post is an tutorial about custom template for slingshot, you can reference “sku” parameter about default value.
https://elliotthamai.wordpress.com/2014/11/15/using-custom-arm-templates-with-the-deploy-to-azure-button/
