### ISSUE TITLE
[Idea] Installation count

### ISSUE THREAD

**Issue by kendaleiv** [projectkudu/slingshot#72]
A count of the number of installs.

Perhaps this could be accomplished using Google Analytics or similar by adding the necessary information to the `azuredeploy.json` and making the tracking call in the `ARMController` `Deploy` action (if that works / makes sense).

Thoughts? Does this seem reasonable, or would it be more appropriate for the deployed application to handle this concern?

**Comment by shrimpy** [comment]
@kendaleiv we have telemetry on "deploy.azure.com" using Azure Insights to count total number of deployment. 

Are you suggesting feature to allow end user to track their own deployment? In this case it is better to do it on your application level, since "slingshot" is a stateless service, it doesn`t have the knowledge to map a specific deployment to a specific user/application.

**Comment by kendaleiv** [comment]
My thought was for a _this many users have installed this project using the badge_ feature.

It sounds like this might be best accomplished inside the actual application, if desired.

Thanks for the reply!
